version: '3.5'
services:

  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki-deploy-dev
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build:
      context: ./deploy/middleware
      dockerfile: Dockerfile
    depends_on:
      - fuseki
    volumes:
      - ./middleware/logs:/archipelago/middleware/logs
      - ./middleware/jwt:/archipelago/middleware/jwt
      - ./middleware/uploads:/archipelago/middleware/uploads
    environment:
      - SEMAPPS_SPARQL_ENDPOINT=http://fuseki-deploy-dev:3030/
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=admin
      - SEMAPPS_HOME_URL=http://localhost:3000/
      - SEMAPPS_OIDC_ISSUER=https://login.lescommuns.org//auth/realms/master/
      - SEMAPPS_OIDC_CLIENT_ID=semapps-dp
      - SEMAPPS_REDIS_URL=redis://redis:6379/0
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"

  frontend:
    build:
      context: ./deploy/frontend
      dockerfile: Dockerfile
    #volumes:
      #- ./addOn/MyLogo.png:/archipelago/frontend/addOn/logo192.png
      #- ./addOn/MyLogo.png:/archipelago/frontend/addOn/logo512.png
      #- ./addOn/App.js:/archipelago/frontend/src/App.js
      #- ./addOn/myFavicon.ico:/archipelago/frontend/addOn/favicon.ico
      #- ./addOn/myIndex.html:/archipelago/frontend/addOn/index.html
    environment:
      - REACT_APP_MAPBOX_ACCESS_TOKEN=MyMapBoxToken
      - PORT=4000
    networks:
      - semapps
    ports:
      - "4000:4000"
    command: bash -c "yarn build && serve -s build"

  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - semapps
    command: ["redis-server", "--appendonly", "yes"]

networks:
  semapps:
    name: semapps_network
